/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const GetlatestblockLazyImport = createFileRoute('/get_latest_block')()
const GetbalanceLazyImport = createFileRoute('/get_balance')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const GetlatestblockLazyRoute = GetlatestblockLazyImport.update({
  path: '/get_latest_block',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/get_latest_block.lazy').then((d) => d.Route),
)

const GetbalanceLazyRoute = GetbalanceLazyImport.update({
  path: '/get_balance',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/get_balance.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_balance': {
      id: '/get_balance'
      path: '/get_balance'
      fullPath: '/get_balance'
      preLoaderRoute: typeof GetbalanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_latest_block': {
      id: '/get_latest_block'
      path: '/get_latest_block'
      fullPath: '/get_latest_block'
      preLoaderRoute: typeof GetlatestblockLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/get_balance': typeof GetbalanceLazyRoute
  '/get_latest_block': typeof GetlatestblockLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/get_balance': typeof GetbalanceLazyRoute
  '/get_latest_block': typeof GetlatestblockLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/get_balance': typeof GetbalanceLazyRoute
  '/get_latest_block': typeof GetlatestblockLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/get_balance' | '/get_latest_block'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/get_balance' | '/get_latest_block'
  id: '__root__' | '/' | '/get_balance' | '/get_latest_block'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GetbalanceLazyRoute: typeof GetbalanceLazyRoute
  GetlatestblockLazyRoute: typeof GetlatestblockLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GetbalanceLazyRoute: GetbalanceLazyRoute,
  GetlatestblockLazyRoute: GetlatestblockLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/get_balance",
        "/get_latest_block"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/get_balance": {
      "filePath": "get_balance.lazy.tsx"
    },
    "/get_latest_block": {
      "filePath": "get_latest_block.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
